In [186]:
import os
os.getcwd()

'C:\\Users\\sridharvumma\\project\\bigmartsales'

In [187]:
import numpy as np
import pandas as pd

In [188]:
train=pd.read_csv('train_v9rqX0R.csv')
test=pd.read_csv('test_AbJTz2l.csv')

In [247]:
train.head(10)

,Item_Identifier,Item_Weight,Item_Fat_Content,Item_Visibility,Item_Type,Item_MRP,Outlet_Identifier,Outlet_Establishment_Year,Outlet_Size,Outlet_Location_Type,Outlet_Type,Item_Outlet_Sales
0,FDA15,9.300,Low Fat,0.016047,Dairy,249.8092,OUT049,1999,Medium,Tier 1,Supermarket Type1,3735.1380
1,DRC01,5.920,Regular,0.019278,Soft Drinks,48.2692,OUT018,2009,Medium,Tier 3,Supermarket Type2,443.4228
2,FDN15,17.500,Low Fat,0.016760,Meat,141.6180,OUT049,1999,Medium,Tier 1,Supermarket Type1,2097.2700
3,FDX07,19.200,Regular,0.000000,Fruits and Vegetables,182.0950,OUT010,1998,NaN,Tier 3,Grocery Store,732.3800
4,NCD19,8.930,Low Fat,0.000000,Household,53.8614,OUT013,1987,High,Tier 3,Supermarket Type1,994.7052
5,FDP36,10.395,Regular,0.000000,Baking Goods,51.4008,OUT018,2009,Medium,Tier 3,Supermarket Type2,556.6088
6,FDO10,13.650,Regular,0.012741,Snack Foods,57.6588,OUT013,1987,High,Tier 3,Supermarket Type1,343.5528
7,FDP10,NaN,Low Fat,0.127470,Snack Foods,107.7622,OUT027,1985,Medium,Tier 3,Supermarket Type3,4022.7636
8,FDH17,16.200,Regular,0.016687,Frozen Foods,96.9726,OUT045,2002,NaN,Tier 2,Supermarket Type1,1076.5986
9,FDU28,19.200,Regular,0.094450,Frozen Foods,187.8214,OUT017,2007,NaN,Tier 2,Supermarket Type1,4710.5350

In [257]:
test.head()

,Item_Identifier,Item_Weight,Item_Fat_Content,Item_Visibility,Item_Type,Item_MRP,Outlet_Identifier,Outlet_Establishment_Year,Outlet_Size,Outlet_Location_Type,Outlet_Type
0,FDW58,20.750,Low Fat,0.007565,Snack Foods,107.8622,OUT049,1999,Medium,Tier 1,Supermarket Type1
1,FDW14,8.300,reg,0.038428,Dairy,87.3198,OUT017,2007,NaN,Tier 2,Supermarket Type1
2,NCN55,14.600,Low Fat,0.099575,Others,241.7538,OUT010,1998,NaN,Tier 3,Grocery Store
3,FDQ58,7.315,Low Fat,0.015388,Snack Foods,155.0340,OUT017,2007,NaN,Tier 2,Supermarket Type1
4,FDY38,NaN,Regular,0.118599,Dairy,234.2300,OUT027,1985,Medium,Tier 3,Supermarket Type3

In [258]:
train.isnull().sum()

Item_Identifier                 0
Item_Weight                  1463
Item_Fat_Content                0
Item_Visibility                 0
Item_Type                       0
Item_MRP                        0
Outlet_Identifier               0
Outlet_Establishment_Year       0
Outlet_Size                  2410
Outlet_Location_Type            0
Outlet_Type                     0
Item_Outlet_Sales               0
dtype: int64

In [192]:
train['Item_Weight'].value_counts()

12.150    86
17.600    82
13.650    77
11.800    76
15.100    68
          ..
7.560      2
9.420      1
5.400      1
6.520      1
7.685      1
Name: Item_Weight, Length: 415, dtype: int64

In [193]:
train.describe()

,Item_Weight,Item_Visibility,Item_MRP,Outlet_Establishment_Year,Item_Outlet_Sales
count,7060.000000,8523.000000,8523.000000,8523.000000,8523.000000
mean,12.857645,0.066132,140.992782,1997.831867,2181.288914
std,4.643456,0.051598,62.275067,8.371760,1706.499616
min,4.555000,0.000000,31.290000,1985.000000,33.290000
25%,8.773750,0.026989,93.826500,1987.000000,834.247400
50%,12.600000,0.053931,143.012800,1999.000000,1794.331000
75%,16.850000,0.094585,185.643700,2004.000000,3101.296400
max,21.350000,0.328391,266.888400,2009.000000,13086.964800

In [194]:
train.shape

(8523, 12)

In [195]:
train.isna().sum()

Item_Identifier                 0
Item_Weight                  1463
Item_Fat_Content                0
Item_Visibility                 0
Item_Type                       0
Item_MRP                        0
Outlet_Identifier               0
Outlet_Establishment_Year       0
Outlet_Size                  2410
Outlet_Location_Type            0
Outlet_Type                     0
Item_Outlet_Sales               0
dtype: int64

In [196]:
train['Outlet_Type'].unique()

array(['Supermarket Type1', 'Supermarket Type2', 'Grocery Store',
       'Supermarket Type3'], dtype=object)

In [260]:
list(set(train['Item_Identifier']))

['NCQ05',
 'FDZ39',
 'FDY56',
 'FDK51',
 'FDN32',
 'FDT04',
 'NCP42',
 'FDA27',
 'NCX29',
 'FDG60',
 'FDQ27',
 'FDU21',
 'FDH22',
 'FDO28',
 'FDW39',
 'FDX45',
 'FDG50',
 'NCC43',
 'FDM25',
 'NCC06',
 'FDT27',
 'FDU60',
 'FDT57',
 'DRA59',
 'FDH44',
 'FDJ10',
 'NCS54',
 'FDX10',
 'FDQ58',
 'FDT43',
 'FDK04',
 'FDD28',
 'FDN15',
 'DRM49',
 'FDX34',
 'FDD45',
 'FDW40',
 'FDG14',
 'NCH30',
 'NCT41',
 'NCZ29',
 'FDP46',
 'FDH28',
 'FDA58',
 'FDP13',
 'FDX52',
 'FDR57',
 'FDN31',
 'FDJ50',
 'FDI27',
 'FDO60',
 'FDZ55',
 'FDF05',
 'FDK08',
 'NCO07',
 'NCL54',
 'FDU43',
 'FDD41',
 'DRN11',
 'FDY27',
 'FDJ34',
 'FDX49',
 'NCQ02',
 'FDL28',
 'FDO19',
 'NCR41',
 'NCD54',
 'FDV27',
 'FDG21',
 'FDS25',
 'FDH26',
 'FDV26',
 'FDA36',
 'FDS10',
 'NCG07',
 'DRI51',
 'FDI40',
 'FDI44',
 'NCR29',
 'NCA06',
 'FDS52',
 'FDH21',
 'FDV43',
 'FDB21',
 'FDL34',
 'DRE27',
 'FDW32',
 'FDR44',
 'NCJ05',
 'FDK58',
 'FDB12',
 'FDT52',
 'FDJ40',
 'NCL42',
 'FDT45',
 'NCP17',
 'NCY54',
 'FDG38',
 'NCB31',
 'DRE01',
 'NCV18',
 'FDT24',
 'NCK07',
 'FDU55',
 'FDN38',
 'NCP05',
 'NCS41',
 'DRH01',
 'NCK19',
 'FDE36',
 'FDP44',
 'NCL06',
 'FDW34',
 'DRF60',
 'FDS43',
 'NCP18',
 'FDB17',
 'FDN28',
 'DRF27',
 'FDR52',
 'FDB37',
 'FDJ32',
 'FDX57',
 'DRI37',
 'FDV23',
 'FDM03',
 'FDS21',
 'DRK12',
 'FDP28',
 'FDO40',
 'FDA20',
 'FDN08',
 'FDU48',
 'FDN04',
 'FDZ23',
 'NCR54',
 'NCN41',
 'DRJ25',
 'FDH02',
 'FDT37',
 'FDF56',
 'FDU32',
 'FDF59',
 'FDS13',
 'FDJ55',
 'FDA01',
 'FDT28',
 'FDR27',
 'FDK25',
 'FDO31',
 'FDW60',
 'FDM56',
 'FDP21',
 'FDB29',
 'FDM38',
 'DRP35',
 'FDX22',
 'FDL39',
 'FDT16',
 'DRC36',
 'NCB06',
 'FDO57',
 'FDI15',
 'FDQ31',
 'DRG39',
 'FDM13',
 'NCP53',
 'DRF13',
 'FDZ51',
 'FDV51',
 'NCY41',
 'FDQ23',
 'FDK46',
 'NCJ19',
 'FDQ14',
 'DRN47',
 'FDS02',
 'FDZ35',
 'FDS28',
 'FDU13',
 'FDQ10',
 'FDG59',
 'NCD06',
 'DRM48',
 'NCY53',
 'NCR18',
 'FDK43',
 'FDO08',
 'FDL25',
 'FDT48',
 'FDO22',
 'FDT33',
 'DRJ59',
 'FDE46',
 'FDL40',
 'NCC19',
 'FDX15',
 'NCA42',
 'FDJ57',
 'NCL53',
 'FDY08',
 'FDU34',
 'FDD34',
 'FDA02',
 'FDG56',
 'DRN37',
 'FDU20',
 'FDC22',
 'FDZ34',
 'FDA45',
 'FDN21',
 'FDH41',
 'NCO30',
 'DRJ35',
 'FDW45',
 'FDU04',
 'FDO10',
 'FDA48',
 'FDH38',
 'NCN19',
 'NCC07',
 'FDO38',
 'FDJ03',
 'FDZ50',
 'DRJ51',
 'FDM14',
 'FDB08',
 'FDR32',
 'FDJ22',
 'DRN35',
 'NCK30',
 'FDW28',
 'NCE19',
 'FDZ21',
 'FDV36',
 'DRK13',
 'FDI52',
 'FDJ56',
 'FDX08',
 'FDZ01',
 'NCS29',
 'FDN10',
 'FDF29',
 'FDI48',
 'FDF40',
 'FDO21',
 'FDA40',
 'NCT53',
 'FDV03',
 'FDO52',
 'FDL12',
 'FDV34',
 'FDB33',
 'FDU33',
 'DRI13',
 'FDW15',
 'FDV57',
 'NCH54',
 'DRG51',
 'NCF42',
 'NCY05',
 'FDX24',
 'FDD58',
 'FDB32',
 'NCJ30',
 'NCO26',
 'FDB41',
 'FDC56',
 'FDC53',
 'NCQ41',
 'FDP52',
 'FDV07',
 'NCM41',
 'FDZ10',
 'FDM34',
 'FDB39',
 'DRI23',
 'FDM09',
 'NCS18',
 'FDI46',
 'FDC44',
 'DRH59',
 'FDX35',
 'DRI25',
 'FDO03',
 'FDN02',
 'DRL37',
 'FDE10',
 'FDQ04',
 'FDL33',
 'FDN39',
 'FDR36',
 'DRH36',
 'FDA28',
 'FDD48',
 'NCD31',
 'FDM28',
 'DRL35',
 'FDW57',
 'FDL04',
 'DRH39',
 'FDE40',
 'FDL13',
 'FDI58',
 'FDF33',
 'DRF23',
 'NCB19',
 'FDO25',
 'FDH48',
 'FDU01',
 'FDB05',
 'FDT51',
 'FDE04',
 'FDJ07',
 'FDF39',
 'FDH45',
 'FDC11',
 'DRL47',
 'FDR31',
 'NCB07',
 'NCZ41',
 'FDC32',
 'FDD35',
 'DRO35',
 'FDS34',
 'FDD46',
 'FDP49',
 'FDM45',
 'FDH16',
 'FDB11',
 'DRJ11',
 'FDO20',
 'FDZ02',
 'FDV39',
 'FDC04',
 'FDR45',
 'NCM07',
 'FDD32',
 'FDP48',
 'FDW01',
 'FDS40',
 'FDJ20',
 'FDT19',
 'FDV09',
 'FDA38',
 'FDW46',
 'FDN09',
 'FDX01',
 'FDN20',
 'FDA07',
 'FDS24',
 'NCX53',
 'FDC02',
 'NCG18',
 'FDY12',
 'DRE03',
 'NCM31',
 'FDX04',
 'DRL11',
 'FDE20',
 'NCL41',
 'DRM47',
 'NCC30',
 'FDC21',
 'FDV33',
 'FDO15',
 'FDT46',
 'FDT22',
 'FDU27',
 'FDV25',
 'FDW03',
 'NCI42',
 'NCM30',
 'FDV20',
 'FDV52',
 'FDR58',
 'FDL08',
 'FDY16',
 'FDW21',
 'FDB44',
 'FDC23',
 'FDP33',
 'FDA34',
 'FDI14',
 'FDB38',
 'FDM46',
 'FDS39',
 'FDR15',
 'FDJ27',
 'NCH43',
 'FDE51',
 'FDZ15',
 'NCX41',
 'FDV48',
 'FDB03',
 'FDB53',
 'DRM59',
 'FDM15',
 'FDE52',
 'FDX51',
 'FDO49',
 'FDQ09',
 'FDO44',
 'DRH23',
 'NCJ06',
 'FDT03',
 'FDS56',
 'NCN55',
 'FDF45',
 'NCT30',
 'FDN48',
 'FDO36',
 'DRH15',
 'FDV16',
 'FDZ45',
 'FDZ47',
 'FDM33',
 'FDY14',
 'FDT59',
 'NCL55',
 'FDA04',
 'FDX56',
 'FDV44',
 'NCO53',
 'DRF25',
 'FDT26',
 'FDX03',
 'FDI08',
 'DRD12',
 'NCS38',
 'FDE58',
 'FDR09',
 'FDD08',
 'DRF51',
 'FDD02',
 'FDL14',
 'FDA37',
 'NCF19',
 'FDI22',
 'DRA12',
 'FDT09',
 'FDN56',
 'FDI38',
 'FDP45',
 'NCM42',
 'FDY15',
 'FDE41',
 'FDP39',
 'FDP20',
 'FDS57',
 'DRK47',
 'FDH56',
 'FDJ12',
 'FDY32',
 'FDM04',
 'FDK20',
 'FDN57',
 'NCA17',
 'FDY22',
 'NCT05',
 'FDR20',
 'NCX54',
 'FDU56',
 'NCX17',
 'FDH19',
 'FDW02',
 'FDU26',
 'FDK48',
 'NCP55',
 'FDH32',
 'FDI45',
 'FDQ32',
 'FDK26',
 'FDN12',
 'FDZ31',
 'FDK22',
 'FDY40',
 'DRG23',
 'DRM37',
 'NCF55',
 'FDP16',
 'NCH42',
 'FDF22',
 'DRD15',
 'FDN58',
 'FDK44',
 'NCM19',
 'FDZ56',
 'DRM23',
 'NCE18',
 'FDP37',
 'FDB52',
 'FDF11',
 'NCQ42',
 'NCT29',
 'FDU02',
 'FDD10',
 'FDY02',
 'FDX19',
 'FDE24',
 'FDT49',
 'FDM24',
 'DRJ47',
 'NCP06',
 'FDP27',
 'FDM10',
 'FDU07',
 'FDH46',
 'NCN29',
 'FDT47',
 'NCT17',
 'FDA19',
 'FDC46',
 'FDY01',
 'FDK36',
 'FDN51',
 'FDZ27',
 'FDW43',
 'FDC03',
 'FDB22',
 'FDA16',
 'FDO09',
 'NCB30',
 'FDZ20',
 'FDY04',
 'NCL31',
 'FDR47',
 'DRD27',
 'FDP19',
 'FDM51',
 'NCQ18',
 'FDA22',
 'FDP12',
 'FDM12',
 'FDZ13',
 'FDQ26',
 'DRB48',
 'FDR37',
 'FDC60',
 'DRN59',
 'NCB55',
 'FDZ04',
 'FDX25',
 'NCF54',
 'FDV55',
 'DRG48',
 'FDS20',
 'FDD33',
 'FDN34',
 'FDV10',
 'DRG27',
 'NCJ17',
 'NCT42',
 'DRL59',
 'FDW07',
 'FDY48',
 'FDX46',
 'FDU22',
 'FDO11',
 'NCN26',
 'FDL20',
 'FDC59',
 'FDD38',
 'NCW41',
 'FDE17',
 'FDL45',
 'FDF21',
 'FDS16',
 'FDQ08',
 'FDC51',
 'FDF34',
 'FDW55',
 'NCS30',
 'FDM21',
 'FDR25',
 'FDQ45',
 'NCL30',
 'FDY43',
 'FDJ08',
 'FDZ26',
 'FDZ48',
 'FDB57',
 'FDU36',
 'NCW29',
 'FDC14',
 'FDA33',
 'FDZ43',
 'FDJ41',
 'FDR48',
 'FDH27',
 'NCV05',
 'DRM11',
 'FDW22',
 'DRD13',
 'FDC09',
 'FDX20',
 'FDE45',
 'FDT15',
 'FDW56',
 'FDJ58',
 'FDY51',
 'FDV11',
 'FDA13',
 'FDC57',
 'NCM17',
 'FDY44',
 'NCQ17',
 'FDW23',
 'DRK49',
 'FDZ40',
 'FDV56',
 'NCQ50',
 'NCU18',
 'FDR35',
 'FDQ11',
 'NCI17',
 'FDU35',
 'FDK38',
 'FDX13',
 'FDA57',
 'DRH51',
 'FDL26',
 'FDQ56',
 'NCE30',
 'FDF50',
 'FDK16',
 'FDX55',
 'FDU52',
 'FDG12',
 'NCZ53',
 'FDG46',
 'NCY06',
 'FDC35',
 'FDL03',
 'FDA51',
 'NCQ38',
 'FDV60',
 'DRJ24',
 'FDA56',
 'FDW14',
 'DRG01',
 'NCW05',
 'FDD47',
 'FDR22',
 'FDO34',
 'FDL09',
 'FDR56',
 'FDI60',
 'FDL58',
 'NCI18',
 'NCO05',
 'FDN01',
 'FDS26',
 'FDV47',
 'NCN54',
 'DRG03',
 'FDI28',
 'FDE33',
 'NCT06',
 'FDM27',
 'FDV14',
 'FDU15',
 'NCM05',
 'FDE50',
 'FDB28',
 'FDT25',
 'FDQ59',
 'NCH06',
 'NCM55',
 'NCD55',
 'FDH10',
 'FDP23',
 'FDS46',
 'FDZ58',
 'FDT02',
 'FDQ21',
 'FDA46',
 'FDJ38',
 'FDA09',
 'DRY23',
 'FDC52',
 'DRF36',
 'FDV01',
 'NCU53',
 'FDV59',
 'NCO17',
 'FDP57',
 'FDC50',
 'DRJ13',
 'NCZ42',
 'FDC08',
 'FDP56',
 'FDN52',
 'FDY50',
 'FDD36',
 'FDA11',
 'FDZ16',
 'FDE39',
 'DRH49',
 'FDH31',
 'FDD53',
 'NCF31',
 'DRK01',
 'FDV21',
 'FDI32',
 'FDF32',
 'FDR51',
 'FDI50',
 'FDS12',
 'FDN33',
 'DRH13',
 'FDI56',
 'FDS11',
 'FDB59',
 'FDK24',
 'FDR60',
 'FDD29',
 'FDL43',
 'NCR53',
 'FDX43',
 'FDW58',
 'FDD59',
 'NCW53',
 'FDK40',
 'FDE29',
 'NCE54',
 'NCJ18',
 'FDI12',
 'DRG11',
 'NCR06',
 'FDW33',
 'NCG54',
 'FDP04',
 'FDQ40',
 'NCW54',
 'NCG19',
 'FDM58',
 'DRA24',
 'FDD52',
 'FDX07',
 'FDM40',
 'DRK23',
 'FDG58',
 'DRM35',
 'FDO27',
 'DRI39',
 'FDY38',
 'NCU42',
 'FDN25',
 'FDU49',
 'FDC41',
 'DRE25',
 'FDB60',
 'FDF38',
 'NCS42',
 'NCQ29',
 'FDU47',
 'FDG16',
 'DRF48',
 'FDU10',
 'FDS04',
 'DRL60',
 'NCX05',
 'FDP32',
 'FDY35',
 'FDU09',
 'FDH35',
 'FDD40',
 'NCA05',
 'FDE38',
 'FDF35',
 'FDB47',
 'FDJ53',
 'NCG30',
 'FDH57',
 'FDW50',
 'FDQ12',
 'FDC40',
 'FDY28',
 'FDT23',
 'NCS05',
 'FDZ22',
 'NCJ54',
 'NCP02',
 'NCM53',
 'NCF18',
 'FDU25',
 'FDJ14',
 'FDL27',
 'FDV08',
 'FDW27',
 'DRC25',
 'FDK09',
 'FDG02',
 'FDN49',
 'FDW16',
 'NCE07',
 'FDA47',
 'NCX42',
 'FDG05',
 'FDU03',
 'FDP07',
 'FDX40',
 'NCK17',
 'FDM52',
 'NCP29',
 'FDN50',
 'FDA14',
 'FDE11',
 'NCW30',
 'NCU06',
 'DRK39',
 'FDV35',
 'FDG20',
 'FDN22',
 'FDL51',
 'NCN05',
 'FDS19',
 'DRI59',
 'FDT32',
 'FDT40',
 'FDV15',
 'FDY21',
 'FDL32',
 'FDP40',
 'FDI20',
 'FDU58',
 'FDE22',
 'FDX09',
 'DRE15',
 'FDU12',
 'FDY10',
 'FDX31',
 'DRH03',
 'FDH14',
 'NCM26',
 'FDH24',
 'FDK15',
 'FDQ01',
 'FDH17',
 'NCM43',
 'FDE08',
 'FDO58',
 'FDM01',
 'FDB56',
 'FDG44',
 'FDW12',
 'NCU41',
 'FDL24',
 'NCJ29',
 'FDK50',
 'FDY09',
 'FDK41',
 'FDJ16',
 'FDQ51',
 'NCB43',
 'FDK34',
 'FDI09',
 'FDD56',
 'FDG52',
 'FDV50',
 'FDG35',
 'FDH53',
 'FDZ08',
 'NCA41',
 'NCO18',
 'FDW04',
 'FDU31',
 'FDP24',
 'FDT38',
 'NCK29',
 'DRL49',
 'NCJ31',
 'FDP51',
 'NCE43',
 'NCO54',
 'DRZ24',
 'NCI06',
 'NCQ43',
 'FDR16',
 'FDO23',
 'FDT13',
 'NCS06',
 'NCO02',
 'FDW51',
 'NCQ54',
 'DRI11',
 'FDH33',
 'FDZ12',
 'DRE12',
 'NCU17',
 'NCY42',
 'FDX39',
 'FDL21',
 'NCA29',
 'FDU51',
 'FDE02',
 'NCR17',
 'FDZ44',
 'DRB25',
 'FDD39',
 'DRK37',
 'FDC48',
 'FDJ15',
 'FDH52',
 'FDB35',
 'FDG47',
 'NCL18',
 'NCV17',
 'FDG33',
 'FDC37',
 'FDD17',
 'NCU30',
 'FDR03',
 'FDT56',
 'FDE59',
 'FDL22',
 'FDS47',
 'FDU11',
 'NCR38',
 'NCQ06',
 'NCC42',
 'FDB10',
 'NCO55',
 'NCL05',
 'FDQ13',
 'FDV02',
 'FDA39',
 'FDQ39',
 'FDR04',
 'FDF17',
 'FDD44',
 'NCP43',
 'FDH09',
 'FDY57',
 'FDD26',
 'DRG37',
 'NCF43',
 'FDO24',
 'NCY18',
 'DRF03',
 'FDN45',
 'FDY55',
 'NCI55',
 'FDX02',
 'FDT07',
 'NCV30',
 'FDV12',
 'FDE09',
 'NCO14',
 'NCC55',
 'FDY46',
 'NCP54',
 'FDZ60',
 'NCY17',
 'FDT35',
 'FDT14',
 'DRL23',
 'FDW26',
 'DRD49',
 'NCD30',
 'NCW06',
 'FDO39',
 'FDD51',
 'NCY30',
 'FDP38',
 'FDA21',
 'FDG41',
 'FDQ37',
 'FDR01',
 'FDM60',
 'NCN06',
 'FDH12',
 'FDI24',
 'FDQ03',
 'NCD18',
 'NCS17',
 'NCI31',
 'FDO16',
 'NCC18',
 'FDL46',
 'FDH08',
 'FDL52',
 'FDA49',
 'NCP41',
 'FDR13',
 'FDX26',
 'FDD57',
 'FDE05',
 'FDF16',
 'FDY34',
 'FDS45',
 'FDV28',
 'FDZ09',
 'FDY49',
 'FDC05',
 'FDU40',
 'FDR43',
 'FDX32',
 'FDK55',
 ...]

In [259]:
train[train['Item_Identifier']=='FDU28']

,Item_Identifier,Item_Weight,Item_Fat_Content,Item_Visibility,Item_Type,Item_MRP,Outlet_Identifier,Outlet_Establishment_Year,Outlet_Size,Outlet_Location_Type,Outlet_Type,Item_Outlet_Sales
9,FDU28,19.2,Regular,0.094450,Frozen Foods,187.8214,OUT017,2007,NaN,Tier 2,Supermarket Type1,4710.5350
6362,FDU28,NaN,Regular,0.164439,Frozen Foods,188.4214,OUT019,1985,Small,Tier 1,Grocery Store,376.8428
6419,FDU28,19.2,Regular,0.094301,Frozen Foods,187.5214,OUT018,2009,Medium,Tier 3,Supermarket Type2,1695.7926
7597,FDU28,NaN,Regular,0.093464,Frozen Foods,189.1214,OUT027,1985,Medium,Tier 3,Supermarket Type3,2261.0568
8419,FDU28,19.2,Regular,0.093918,Frozen Foods,189.8214,OUT046,1997,Small,Tier 1,Supermarket Type1,942.1070

In [198]:
train_data= pd.DataFrame()

for item in list(set(train['Item_Identifier'])):
    temp= train[train['Item_Identifier']== item].copy()
    
    temp['Item_Weight'].fillna(temp['Item_Weight'].mean(),inplace=True)
    train_data = train_data.append(temp)
print(train_data)

     Item_Identifier  Item_Weight Item_Fat_Content  Item_Visibility  \
677            NCQ05       11.395               LF         0.000000
882            NCQ05       11.395          Low Fat         0.036164
4058           NCQ05       11.395          Low Fat         0.021640
5768           NCQ05       11.395               LF         0.021602
6041           NCQ05       11.395          Low Fat         0.000000
...              ...          ...              ...              ...
285            FDT39        6.260          Regular         0.009866
2678           FDT39        6.260              reg         0.016517
3434           FDT39        6.260          Regular         0.009924
6629           FDT39        6.260          Regular         0.009888
6803           FDT39        6.260              reg         0.009883

               Item_Type  Item_MRP Outlet_Identifier  \
677   Health and Hygiene  151.6708            OUT013
882   Health and Hygiene  150.1708            OUT010
4058  Health and Hygiene  150.1708            OUT049
5768  Health and Hygiene  149.1708            OUT035
6041  Health and Hygiene  152.0708            OUT027
...                  ...       ...               ...
285                 Meat  151.1366            OUT035
2678                Meat  151.1366            OUT010
3434                Meat  152.8366            OUT017
6629                Meat  150.7366            OUT045
6803                Meat  149.8366            OUT049

      Outlet_Establishment_Year Outlet_Size Outlet_Location_Type  \
677                        1987        High               Tier 3
882                        1998         NaN               Tier 3
4058                       1999      Medium               Tier 1
5768                       2004       Small               Tier 2
6041                       1985      Medium               Tier 3
...                         ...         ...                  ...
285                        2004       Small               Tier 2
2678                       1998         NaN               Tier 3
3434                       2007         NaN               Tier 2
6629                       2002         NaN               Tier 2
6803                       1999      Medium               Tier 1

            Outlet_Type  Item_Outlet_Sales
677   Supermarket Type1          3460.8284
882       Grocery Store           300.9416
4058  Supermarket Type1          2708.4744
5768  Supermarket Type1          2708.4744
6041  Supermarket Type3          2106.5912
...                 ...                ...
285   Supermarket Type1          2267.0490
2678      Grocery Store           453.4098
3434  Supermarket Type1          3778.4150
6629  Supermarket Type1          2418.1856
6803  Supermarket Type1          1964.7758

[8523 rows x 12 columns]

In [261]:
train_data.tail()

,Item_Identifier,Item_Weight,Item_Fat_Content,Item_Visibility,Item_Type,Item_MRP,Outlet_Identifier,Outlet_Establishment_Year,Outlet_Size,Outlet_Location_Type,Outlet_Type,Item_Outlet_Sales
285,FDT39,6.26,Regular,0.009866,Meat,151.1366,OUT035,2004,Small,Tier 2,Supermarket Type1,2267.0490
2678,FDT39,6.26,Regular,0.016517,Meat,151.1366,OUT010,1998,Small,Tier 3,Grocery Store,453.4098
3434,FDT39,6.26,Regular,0.009924,Meat,152.8366,OUT017,2007,Small,Tier 2,Supermarket Type1,3778.4150
6629,FDT39,6.26,Regular,0.009888,Meat,150.7366,OUT045,2002,Small,Tier 2,Supermarket Type1,2418.1856
6803,FDT39,6.26,Regular,0.009883,Meat,149.8366,OUT049,1999,Medium,Tier 1,Supermarket Type1,1964.7758

In [200]:
test_data= pd.DataFrame()

for item in list(set(test['Item_Identifier'])):
    temp= test[test['Item_Identifier']== item].copy()
    
    temp['Item_Weight'].fillna(temp['Item_Weight'].mean(),inplace=True)
    test_data = test_data.append(temp)
print(test_data)

     Item_Identifier  Item_Weight Item_Fat_Content  Item_Visibility  \
1405           NCQ05       11.395          Low Fat         0.021694
4356           NCQ05       11.395          Low Fat         0.021606
1651           FDZ39       19.700          Regular         0.030170
3368           FDZ39       19.700          Regular         0.018053
3416           FDZ39       19.700          Regular         0.018010
...              ...          ...              ...              ...
100            FDT39        6.260          Regular         0.009908
371            FDT39        6.260          Regular         0.017277
1437           FDT39        6.260              reg         0.009820
2334           FDT39        6.260          Regular         0.009860
4520           FDT39        6.260          Regular         0.009868

               Item_Type  Item_MRP Outlet_Identifier  \
1405  Health and Hygiene  150.0708            OUT018
4356  Health and Hygiene  150.0708            OUT046
1651                Meat  103.7990            OUT010
3368                Meat  103.3990            OUT049
3416                Meat  103.6990            OUT013
...                  ...       ...               ...
100                 Meat  151.1366            OUT018
371                 Meat  150.7366            OUT019
1437                Meat  152.7366            OUT027
2334                Meat  151.8366            OUT013
4520                Meat  149.1366            OUT046

      Outlet_Establishment_Year Outlet_Size Outlet_Location_Type  \
1405                       2009      Medium               Tier 3
4356                       1997       Small               Tier 1
1651                       1998         NaN               Tier 3
3368                       1999      Medium               Tier 1
3416                       1987        High               Tier 3
...                         ...         ...                  ...
100                        2009      Medium               Tier 3
371                        1985       Small               Tier 1
1437                       1985      Medium               Tier 3
2334                       1987        High               Tier 3
4520                       1997       Small               Tier 1

            Outlet_Type
1405  Supermarket Type2
4356  Supermarket Type1
1651      Grocery Store
3368  Supermarket Type1
3416  Supermarket Type1
...                 ...
100   Supermarket Type2
371       Grocery Store
1437  Supermarket Type3
2334  Supermarket Type1
4520  Supermarket Type1

[5681 rows x 11 columns]

In [262]:
test_data.head()

,Item_Identifier,Item_Weight,Item_Fat_Content,Item_Visibility,Item_Type,Item_MRP,Outlet_Identifier,Outlet_Establishment_Year,Outlet_Size,Outlet_Location_Type,Outlet_Type
1405,NCQ05,11.395,Low Fat,0.021694,Health and Hygiene,150.0708,OUT018,2009,Medium,Tier 3,Supermarket Type2
4356,NCQ05,11.395,Low Fat,0.021606,Health and Hygiene,150.0708,OUT046,1997,Small,Tier 1,Supermarket Type1
1651,FDZ39,19.700,Regular,0.030170,Meat,103.7990,OUT010,1998,Small,Tier 3,Grocery Store
3368,FDZ39,19.700,Regular,0.018053,Meat,103.3990,OUT049,1999,Medium,Tier 1,Supermarket Type1
3416,FDZ39,19.700,Regular,0.018010,Meat,103.6990,OUT013,1987,High,Tier 3,Supermarket Type1

In [202]:
# train['Item_Weight'].value_counts().idxmax()
train_data.isnull().sum()

Item_Identifier                 0
Item_Weight                     4
Item_Fat_Content                0
Item_Visibility                 0
Item_Type                       0
Item_MRP                        0
Outlet_Identifier               0
Outlet_Establishment_Year       0
Outlet_Size                  2410
Outlet_Location_Type            0
Outlet_Type                     0
Item_Outlet_Sales               0
dtype: int64

In [218]:
test_data.isnull().sum()

Item_Identifier                 0
Item_Weight                    20
Item_Fat_Content                0
Item_Visibility                 0
Item_Type                       0
Item_MRP                        0
Outlet_Identifier               0
Outlet_Establishment_Year       0
Outlet_Size                  1606
Outlet_Location_Type            0
Outlet_Type                     0
dtype: int64

In [206]:
train_data.loc[train_data['Item_Weight'].isnull(),:]

,Item_Identifier,Item_Weight,Item_Fat_Content,Item_Visibility,Item_Type,Item_MRP,Outlet_Identifier,Outlet_Establishment_Year,Outlet_Size,Outlet_Location_Type,Outlet_Type,Item_Outlet_Sales
4187,FDE52,NaN,Regular,0.029742,Dairy,88.9514,OUT027,1985,Medium,Tier 3,Supermarket Type3,3453.5046
927,FDN52,NaN,Regular,0.130933,Frozen Foods,86.9198,OUT027,1985,Medium,Tier 3,Supermarket Type3,1569.9564
5022,FDQ60,NaN,Regular,0.191501,Baking Goods,121.2098,OUT019,1985,Small,Tier 1,Grocery Store,120.5098
1922,FDK57,NaN,Low Fat,0.079904,Snack Foods,120.0440,OUT027,1985,Medium,Tier 3,Supermarket Type3,4434.2280

In [207]:
train_prod_codes = list(train_data[train_data['Item_Weight'].isnull()]['Item_Identifier'])
train_prod_codes

['FDE52', 'FDN52', 'FDQ60', 'FDK57']

In [208]:
test_prod_codes = list(test_data[test_data['Item_Weight'].isnull()]['Item_Identifier'])
test_prod_codes

['FDG50',
 'FDG50',
 'FDF05',
 'FDP28',
 'DRN47',
 'FDO22',
 'NCJ30',
 'FDI45',
 'FDI45',
 'FDF22',
 'FDF22',
 'FDL58',
 'FDL58',
 'FDY57',
 'FDF04',
 'FDG57',
 'FDG09',
 'FDJ09',
 'FDH58',
 'FDT21']

In [209]:
# Till 'FDG50', it is a dataframe, iloc[0] gives that row, access 'Item_weight' value 
#  train[train['Item_Identifier'] == 'FDG57'].iloc[0]['Item_Weight']
train[train['Item_Identifier'] == 'FDG57'].iloc[0]['Item_Weight']

14.7

In [210]:
product_price_test = []
for item in test_prod_codes:
    product_price_test.append(train[train['Item_Identifier']== item].iloc[0]['Item_Weight'])
dictionary_test = dict(zip(test_prod_codes,product_price_test))
dictionary_test

{'FDG50': 7.405,
 'FDF05': 17.5,
 'FDP28': 13.65,
 'DRN47': 12.1,
 'FDO22': 13.5,
 'NCJ30': 5.82,
 'FDI45': 13.1,
 'FDF22': 6.865,
 'FDL58': 5.78,
 'FDY57': 20.2,
 'FDF04': 17.5,
 'FDG57': 14.7,
 'FDG09': 20.6,
 'FDJ09': 15.0,
 'FDH58': 12.3,
 'FDT21': 7.42}

In [211]:
product_price_train =[]
for item in train_prod_codes:
    product_price_train.append(test[test['Item_Identifier']== item].iloc[0]['Item_Weight'])
dictionary_train = dict(zip(train_prod_codes, product_price_train))
dictionary_train

{'FDE52': 10.395, 'FDN52': 9.395, 'FDQ60': 6.195, 'FDK57': 10.195}

In [216]:
train_data['Item_Identifier'].map(dictionary_train)

677    NaN
882    NaN
4058   NaN
5768   NaN
6041   NaN
        ..
285    NaN
2678   NaN
3434   NaN
6629   NaN
6803   NaN
Name: Item_Identifier, Length: 8523, dtype: float64

In [213]:
train_data.loc[train_data['Item_Weight'].isnull(),'Item_Weight']

4187   NaN
927    NaN
5022   NaN
1922   NaN
Name: Item_Weight, dtype: float64

In [214]:
test_data.loc[test_data['Item_Weight'].isnull(),'Item_Weight']

1203   NaN
2600   NaN
5346   NaN
5609   NaN
3734   NaN
4298   NaN
3875   NaN
884    NaN
1741   NaN
1571   NaN
2302   NaN
58     NaN
3619   NaN
482    NaN
5615   NaN
1297   NaN
4496   NaN
1300   NaN
882    NaN
3909   NaN
Name: Item_Weight, dtype: float64

In [217]:
train_data[train_data['Item_Weight'].isnull()]['Item_Weight']

4187   NaN
927    NaN
5022   NaN
1922   NaN
Name: Item_Weight, dtype: float64

In [219]:
# have to understand this did not understand well
train_data.loc[train_data['Item_Weight'].isnull(),'Item_Weight']=train_data['Item_Identifier'].map(dictionary_train)

In [220]:
# have to understand this did not understand well
test_data.loc[test_data['Item_Weight'].isnull(),'Item_Weight'] = test_data['Item_Identifier'].map(dictionary_test)

In [221]:
train_data.isnull().sum()

Item_Identifier                 0
Item_Weight                     0
Item_Fat_Content                0
Item_Visibility                 0
Item_Type                       0
Item_MRP                        0
Outlet_Identifier               0
Outlet_Establishment_Year       0
Outlet_Size                  2410
Outlet_Location_Type            0
Outlet_Type                     0
Item_Outlet_Sales               0
dtype: int64

In [222]:
test_data.isnull().sum()

Item_Identifier                 0
Item_Weight                     0
Item_Fat_Content                0
Item_Visibility                 0
Item_Type                       0
Item_MRP                        0
Outlet_Identifier               0
Outlet_Establishment_Year       0
Outlet_Size                  1606
Outlet_Location_Type            0
Outlet_Type                     0
dtype: int64

In [167]:
# train['Item_Weight'].fillna(train['Item_Weight'].value_counts().idxmax(), inplace=True)
train_data['Outlet_Size'].unique()

array(['High', nan, 'Medium', 'Small'], dtype=object)

In [168]:
train_data['Outlet_Size'].value_counts()

Medium    2793
Small     2388
High       932
Name: Outlet_Size, dtype: int64

In [232]:
train_data.loc[train_data['Outlet_Type']=='Grocery Store', 'Outlet_Size'] = 'Small'

In [233]:
train_data.isnull().sum()

Item_Identifier                 0
Item_Weight                     0
Item_Fat_Content                0
Item_Visibility                 0
Item_Type                       0
Item_MRP                        0
Outlet_Identifier               0
Outlet_Establishment_Year       0
Outlet_Size                  1855
Outlet_Location_Type            0
Outlet_Type                     0
Item_Outlet_Sales               0
dtype: int64

In [235]:
test_data.loc[test_data['Outlet_Type']=='Grocery Store', 'Outlet_Size'] = 'Small'

In [236]:
test_data.isnull().sum()

Item_Identifier                 0
Item_Weight                     0
Item_Fat_Content                0
Item_Visibility                 0
Item_Type                       0
Item_MRP                        0
Outlet_Identifier               0
Outlet_Establishment_Year       0
Outlet_Size                  1236
Outlet_Location_Type            0
Outlet_Type                     0
dtype: int64

In [248]:
train_data.loc[train_data['Outlet_Type']=='Supermarket Type1', 'Outlet_Size'] = train_data['Outlet_Size'].fillna('Small')
train_data.loc[train_data['Outlet_Type']=='Supermarket Type2', 'Outlet_Size'] = train_data['Outlet_Size'].fillna('Medium')

In [249]:

test_data.loc[test_data['Outlet_Type']=='Grocery Store', 'Outlet_Size'] = 'Small'
test_data.loc[test_data['Outlet_Type']=='Supermarket Type1', 'Outlet_Size'] = test_data['Outlet_Size'].fillna('Small')
test_data.loc[test_data['Outlet_Type']=='Supermarket Type2', 'Outlet_Size'] = test_data['Outlet_Size'].fillna('Medium')

In [250]:
train_data.isnull().sum()

Item_Identifier              0
Item_Weight                  0
Item_Fat_Content             0
Item_Visibility              0
Item_Type                    0
Item_MRP                     0
Outlet_Identifier            0
Outlet_Establishment_Year    0
Outlet_Size                  0
Outlet_Location_Type         0
Outlet_Type                  0
Item_Outlet_Sales            0
dtype: int64

In [251]:
test_data.isnull().sum()

Item_Identifier              0
Item_Weight                  0
Item_Fat_Content             0
Item_Visibility              0
Item_Type                    0
Item_MRP                     0
Outlet_Identifier            0
Outlet_Establishment_Year    0
Outlet_Size                  0
Outlet_Location_Type         0
Outlet_Type                  0
dtype: int64

In [252]:
train_data['Item_Fat_Content'].value_counts()

Low Fat    5089
Regular    2889
LF          316
reg         117
low fat     112
Name: Item_Fat_Content, dtype: int64

In [253]:
train_data.replace({'LF':'Low Fat','low fat':'Low Fat','reg':'Regular'},inplace=True)
test_data.replace({'LF':'Low Fat','low fat':'Low Fat','reg':'Regular'},inplace=True)

In [254]:
train_data['Outlet_Type'].unique()

array(['Supermarket Type1', 'Grocery Store', 'Supermarket Type3',
       'Supermarket Type2'], dtype=object)

In [255]:
train_data.to_csv('trainData.csv')

In [256]:
test_data.to_csv('testData.csv')

# Data Preprocessing